### ISSUE TITLE
你好，我想设置一个 可以自动给youtube 的评论点赞的功能，请教一些细节

### ISSUE THREAD

**Issue by cheelix** [papple23g/ahkcompiler#11]

**Comment by papple23g** [comment]
在Youtube裡面，對第一則留言按下喜歡的Javascript語法是:

document.querySelectorAll("yt-icon-button.ytd-toggle-button-renderer")[10].click()

其中裡面的數字10，改成11就是對第一則按不喜歡
第二則按喜歡是12，第二則按不喜歡是13，以此類推~
請問您想要的自動化，具體是想要到甚麼樣的程度呢?
