### ISSUE TITLE
[bug]服务器部署起来后, 积木和填表工具的页面访问不了

### ISSUE THREAD

**Issue by pikapikapii** [papple23g/ahkcompiler#17]
**访问了主页面, 页面出现了home page. 但是其他页面访问不了**, 下面是控制台打印的信息:
System check identified no issues (0 silenced).
June 01, 2022 - 16:29:33
Django version 4.0.4, using settings 'ahkcompiler.settings'
Starting development server at http://0.0.0.0:8001/
Quit the server with CTRL-BREAK.
[01/Jun/2022 16:29:39] "GET /ahkblockly HTTP/1.1" 200 1457788
[01/Jun/2022 16:29:46] "GET /ahkblockly HTTP/1.1" 200 1457788

**Comment by papple23g** [comment]
你的 Django 版本好像跟 requirements.txt 上的不同，建議建一個虛擬環境後安裝 requirements.txt 上的模組再運行試試看
