### ISSUE TITLE
离线版依然不能脱离网络

### ISSUE THREAD

**Issue by FanNengHu** [papple23g/ahkcompiler#7]
你好，这个离线版的貌似还是需要网络链接的吧？我在没有网络的电脑上打开，会反应很长时间，并且“转换为ahk语法”下面的文字框是没有的。一旦连上网络，就可以正常打开。

**Comment by papple23g** [comment]
您好~請問您是使用哪一種瀏覽器呢?

**Comment by papple23g** [comment]
目前已釋出 AHK Blockly 1.12.0
若問題仍未解決的話還請再提出，謝謝~
